name: Seblovesyoutiao
favicon: null
layout_spectrum: 1
typography_spectrum: 0.23751
title: Hello World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1f29'
    - '#f6efa1'
    - '#484445'
    - '#a49b7c'
    - '#7b806c'
  brandStrength: 0.25
  lightness: 0.1602024
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
