name: Seblovesyoutiao
favicon: null
layout_spectrum: 0.9165261
typography_spectrum: 0.5
title: Hello World
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3b0a20'
    - '#b7bd7f'
    - '#3e2a36'
    - '#45525a'
    - '#607f70'
  brandStrength: 0.9462621
  lightness: 0.1602024
  saturation: 0.7150084
  rhythmicContrast: 0.3052277
purpose: []
